name: Hola mundo
on:
  pull_request:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v7
      
      - name: Print hello world
        run: node index.js
